name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Git tag to deploy
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch tag
        run: |
          git fetch --all --tags
          git checkout tags/${{ github.event.inputs.tag }} # Ensure the tag exists
          echo "HEAD=$(git rev-parse ${{ github.event.inputs.tag }})" >> $GITHUB_ENV
      - name: setup-inputs
        run: |
          INPUTS='${{ format('{{"environment": "production", "ref": "{0}"}}', env.HEAD) }}'
          echo "INPUTS=${INPUTS}" >> $GITHUB_ENV
          
      - name: test-sha
        run: |
          echo ${{ github.sha }}
