name: Deploy to Staging
on:
  workflow_dispatch:
    inputs:
      version:
        description: Which version are you creating?
        required: true
      ref:
        description: Git ref to deploy
        required: true
        default: develop
jobs:
  deploy-to-staging:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Branch protection OFF
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/ethanmills/actions-test/branches/main/protection
          repository: ${{ github.repository }}
          owner: ethanmills
          required_status_checks: |
            null
          required_pull_request_reviews: |
            null
          enforce_admins: |
            null
          allow_force_pushes: |
            true
          required_linear_history: |
            true
          allow_deletions: |
            null
          restrictions: |
            null
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      - name: Update master
        run: |
          git fetch
          git branch tmp-branch
          git switch main
          git reset --hard tmp-branch --
          git branch -D tmp-branch
          git tag -f ${{ github.event.inputs.version }}
          git push --force origin ${{ github.event.inputs.version }}
          git push --force origin main
          echo "HEAD=$(git rev-parse ${{ github.event.inputs.version }})" >> $GITHUB_ENV
      - name: Branch protection ON
        uses: octokit/request-action@v2.x
        if: always() # Force this step to run so we don't leave master unprotected
        with:
          route: PUT /repos/ethanmills/actions-test/branches/main/protection
          repository: ${{ github.repository }}
          owner: ethanmills
          required_status_checks: |
            strict: true
            contexts:
              - create-pr
                deploy
          required_pull_request_reviews: |
            dismiss_stale_reviews: true
            require_code_owner_reviews: true
          enforce_admins: |
            true
          allow_force_pushes: |
            null
          required_linear_history: |
            true
          allow_deletions: |
            null
          restrictions: |
            null
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
