name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      version:
        description: Which version are you creating?
        required: true
      ref:
        description: Git ref to deploy
        required: true
        default: develop
jobs:
  create-pr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Branch protection OFF
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/ethanmills/actions-test/branches/main/protection
          repository: ${{ github.repository }}
          owner: ethanmills
          enforce_admins: |
            null
          allow_force_pushes: |
            true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Update master
        run: |
          git fetch
          git branch tmp-branch
          git switch main
          git reset --hard tmp-branch --
          git branch -D tmp-branch
          git tag -f $TAGNAME

          git push --force origin $TAGNAME
          git push --force origin main

          echo "HEAD=$(git rev-parse head)" >> $GITHUB_ENV

      - name: Branch protection ON
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/ethanmills/actions-test/branches/master/protection
          repository: ${{ github.repository }}
          owner: ethanmills
          enforce_admins: |
            true
          allow_force_pushes: |
            null
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: setup-inputs
        run: |
          INPUTS='${{ format('{{"environment": "staging", "ref": "{0}"}}', env.HEAD) }}'
          echo "INPUTS=${INPUTS}" >> $GITHUB_ENV

     
